Fix: withdraw fund logic
isle-labs/isle-contract pull request #45
Opened 2024-07-29 14:41 UTC by LouisTsai-Csie

2024-07-29 17:02 UTC, kevinsslin reviewed
Please address the above problems?

2024-07-29 17:08 UTC, kevinsslin requested changes
Please address the above issues.

2024-08-07 15:33 UTC, LouisTsai-Csie commented on contracts/LoanManager.sol
> +        uint256 drawableFunds = loan_.drawableFunds;
Done

2024-08-08 12:46 UTC, Jung0x12 approved these changes

2024-08-09 11:26 UTC, kevinsslin approved these changes

2024-08-09 11:29 UTC, merged